### ISSUE TITLE
Use another source as audio input?

### ISSUE THREAD

**Issue by reedog117** [stephenlb/twitch-tv-obs-subtitles#2]
Is it possible to use a VLC video source as input to your subtitle plugin?

**Comment by stephenlb** [comment]
Hi there!

**Comment by stephenlb** [comment]
This sounds super interesting.  Yes this could be an entry way to provide VLC subtitles.  However additional coding is required to make it work. Timing mechanics for the subtitle time codes needs to be written as new code.  While Twitch TV Subtitles foundation is a good starting place, the extra code needed to make it work needs to be added!  ⭐️ 🌠

**Comment by luminxa** [comment]
Any update on this i was immediately wondering the same thing.. If it had direct audio i think it would pickup the exact words highly accuately

**Comment by stephenlb** [comment]
Yes I found a solution: https://soundflower.en.softonic.com/

Install Soundflower on your computer.  Then select the audio source from your browser using the "microphone" icon. 

![image](https://user-images.githubusercontent.com/45214/80135228-ccec3280-8554-11ea-8c9b-fd3d080da599.png)

**Comment by luminxa** [comment]
> Yes I found a solution: https://soundflower.en.softonic.com/
> 
> Install Soundflower on your computer. Restart. Then select the audio source from your browser using the "microphone" icon ( top right corner in the address bar ).
> 
> ![80136469-97e0df80-8556-11ea-9298-8ed73573e4b8](https://user-images.githubusercontent.com/45214/80136660-e1c9c580-8556-11ea-9bf5-de83ffc089bd.png)

perfect does it clear up accuracy?

**Comment by luminxa** [comment]
ah darn its only for mac.. i need to find a similar solution for pc

**Comment by stephenlb** [comment]
There appears to be a Windows option here: https://superuser.com/a/1133762

Also if that solution doesn't work on your version of Windows, the google search here has several options: https://www.google.com/search?q=windows+desktop+audio+as+microphone

**Comment by skylilack** [comment]
Is it possible to do automatic translation of subtitles? I thought you could do it through a virtual cable.

**Comment by stephenlb** [comment]
Yes.  

Signup and get API keys: https://admin.pubnub.com/#/blocks/23081/import

1. Signup if you haven't (using the link above)
2. Add the translator as described.
3. Get the Microsoft Key
4. Add it to the Secret Vault
5. Run the function on a channel that matches the channel you are using.

This should still be in the free tier.

**Comment by stephenlb** [comment]
The Translation process will introduce latency, the on-screen text will be delayed by 2-3 seconds while the cloud translates your text.

**Comment by skylilack** [comment]
I had problems in step 4-5. Maybe you have a link to some detailed guide for dabbler
![Screenshot_1](https://user-images.githubusercontent.com/64641588/81005775-24dd4000-8e57-11ea-9f30-c47af7e05cf7.png)
![Screenshot_2](https://user-images.githubusercontent.com/64641588/81005777-2575d680-8e57-11ea-9c18-5f3cc33cd3d4.png)
![Screenshot_3](https://user-images.githubusercontent.com/64641588/81005778-260e6d00-8e57-11ea-84c2-34bdf9d06028.png)
![Screenshot_4](https://user-images.githubusercontent.com/64641588/81005780-260e6d00-8e57-11ea-8d91-98e5d9a72594.png)
![Screenshot_5](https://user-images.githubusercontent.com/64641588/81005782-26a70380-8e57-11ea-9a8f-a68684e7c24c.png)

**Comment by stephenlb** [comment]
Ah yes, I see the issue.

Put the Microsoft Key as follows:

![image](https://user-images.githubusercontent.com/45214/81017111-8df09380-8e16-11ea-903c-251b5c47ed9c.png)

We are testing this now and will confirm.  Note that we'll need to update the code:

change this line:

`let text = request.message.text;`

to 

`let text = request.message.phrase;`

**Comment by stephenlb** [comment]
Also you'll want to set the language you want translated.

`let lang = request.message.language;`
to
`let lang = "zh"; // to Mandarin`
`let lang = "es"; // to Spanish`

![image](https://user-images.githubusercontent.com/45214/81017774-0d329700-8e18-11ea-9c1a-358cd58416f8.png)

**Comment by stephenlb** [comment]
Make sure to match your `Channel`: 
![image](https://user-images.githubusercontent.com/45214/81017946-4b2fbb00-8e18-11ea-8b60-7662529ebfe0.png)

This will be visible in the URL: https://stephenlb.github.io/twitch-tv-obs-subtitles/subtitles.html?subkey=sub-c-79b0a26a-80a9-11e8-8f4a-96bbd71e7d14&pubkey=pub-c-fd9b97a4-7b78-4ae1-a21e-3614f2b6debe&`channel=1588208805983537980353`&style=

**Comment by stephenlb** [comment]
![subtitles-translated](https://user-images.githubusercontent.com/45214/81018927-5be13080-8e1a-11ea-8c8d-c8f182ce2a80.gif)



This line needed to be added to overwrite the original phrase so it showed up in OBS:

![image](https://user-images.githubusercontent.com/45214/81018832-22a8c080-8e1a-11ea-9a40-ab0de09c7820.png)

        request.message.phrase           = request.message.data.text;

Here is the fully updated code block:

```javascript
// Demo URL https://codepen.io/team/PubNub/pen/rdQMaN

// ALERT!  
// YOU NEED TO ADD YOUR MICROSFOT API KEY 'Ocp-Apim-Subscription-Key'
//
// 1.) Click "My Secrets" button.  
// 2.) Add a new Secret 'Ocp-Apim-Subscription-Key'
// 3.) Paste in your Microsoft Translator V3 API Key
// 4.) Save
// 5.) Restart/Start your Module
//

const xhr   = require('xhr');
const vault = require('vault');

export default request => { 
    // Capture Text and Language to Translate
    let text = request.message.phrase   || request.message.text;
    let lang = request.message.language || "fr";
    let data = request.message.data     || {};

    // Translate using Microsoft V3 Translator API
    return translate( text, lang ).then( result => {
        request.message.data             = request.message.data || {};
        request.message.data.translation = result;
        request.message.data.text        = result.translations[0]['text'];
        request.message.phrase           = request.message.data.text;
        return request.ok();
    } ).catch( error => {
        console.error(error);
        return request.ok();
    } );
};

// ------------------------------------
// Microsoft Translator API V3
// ------------------------------------
// Microsoft Response Format
// { detectedLanguage : { language : "en", score : 1.0 }, 
//   translations     : [{ text : text, to : language }] }
function translate( text='hello', language='zh-HH' ) {
    return new Promise( ( resolve, reject ) => {
        return vault.get('Ocp-Apim-Subscription-Key').then( oask => {
            if (!oask) return reject("Missing 'Ocp-Apim-Subscription-Key'");
            let headers = {};
            let opts    = {
                host    : 'https://dev.microsofttranslator.com'
            ,   method  : 'POST'
            ,   headers : headers
            ,   path    : '/translate?api-version=3.0'
            ,   to      : '&to=' + language
            ,   body    : JSON.stringify([{ Text : text }])
            };

            headers['Content-Type']              = 'application/json';
            headers['Ocp-Apim-Subscription-Key'] = oask;

            let uri = opts.host + opts.path + opts.to;
            return xhr.fetch( uri, opts )
                .then(    res => resolve(JSON.parse(res.body)[0]) )
                .catch( error => reject(error) );
        } ).catch( error => {
            return reject(error);
        } );
    } );
}
```

**Comment by skylilack** [comment]
Maybe I'm inserting the wrong key. Is the program able to translate Russian?
![Screenshot_6](https://user-images.githubusercontent.com/64641588/81026016-62ef5980-8e81-11ea-9b61-ff19fb7b3b77.png)
![Screenshot_7](https://user-images.githubusercontent.com/64641588/81026121-bb265b80-8e81-11ea-836f-8e3e8aa913e4.png)
![Screenshot_8](https://user-images.githubusercontent.com/64641588/81026123-bbbef200-8e81-11ea-99e3-cebb081eb936.png)

**Comment by skylilack** [comment]
![Screenshot_9](https://user-images.githubusercontent.com/64641588/81026238-0fc9d680-8e82-11ea-9983-c1318a08985f.png)

**Comment by skylilack** [comment]
I tried all the variations of the key permutation
![Screenshot_10](https://user-images.githubusercontent.com/64641588/81068034-5f42ed80-8ee8-11ea-8318-80e848199daf.png)

**Comment by skylilack** [comment]
I haven’t touched the Russian language yet. I inserted the keys correctly, and inserted your input into mine, launched it.
![Screenshot_11](https://user-images.githubusercontent.com/64641588/81069173-358ac600-8eea-11ea-9dfb-9c24fd199970.png)

**Comment by skylilack** [comment]
I tried to interchange the keys to probably eliminate this problem
![Screenshot_8](https://user-images.githubusercontent.com/64641588/81069562-ba75df80-8eea-11ea-82a2-d911932558fd.png)
![Uploading Screenshot_10.png…]()

**Comment by skylilack** [comment]
I tried to interchange the keys to probably eliminate this problem
![Screenshot_8](https://user-images.githubusercontent.com/64641588/81069562-ba75df80-8eea-11ea-82a2-d911932558fd.png)
![Screenshot_10](https://user-images.githubusercontent.com/64641588/81069567-bb0e7600-8eea-11ea-83f7-5d2a3e1839fd.png)

**Comment by skylilack** [comment]
I tried to interchange the keys to probably eliminate this problem
![Screenshot_8](https://user-images.githubusercontent.com/64641588/81069608-c95c9200-8eea-11ea-865c-d8a941003cbd.png)
![Screenshot_10](https://user-images.githubusercontent.com/64641588/81069609-c9f52880-8eea-11ea-9558-3fc1ec54de36.png)

**Comment by skylilack** [comment]
![Screenshot_12](https://user-images.githubusercontent.com/64641588/81070184-9070ed00-8eeb-11ea-9595-05adc382f488.png)

**Comment by stephenlb** [comment]
Make sure to add the `Vault Key` like this:

![image](https://user-images.githubusercontent.com/45214/81017111-8df09380-8e16-11ea-903c-251b5c47ed9c.png)
> In the picture, "SECRET KEY" refers to the Microsoft Translator API Key.

**Comment by skylilack** [comment]
I am 100% sure that I entered the correct key in the string
![Screenshot_13](https://user-images.githubusercontent.com/64641588/81104480-3ee05680-8f1b-11ea-8b80-1b1f5f64d221.png)

**Comment by skylilack** [comment]
I'm sure that in the value column, I am inserting the correct Micrsoft Translete API key. Maybe I’m inserting the wrong key in the left column (secret key), I take it to the application on the pubNub website
![Screenshot_13](https://user-images.githubusercontent.com/64641588/81104886-d5147c80-8f1b-11ea-93d3-c6f0fcd59e2c.png)

**Comment by skylilack** [comment]
I go to microsoft Azure and take the key there and paste it into the Value column
![Screenshot_14](https://user-images.githubusercontent.com/64641588/81109132-50792c80-8f22-11ea-8874-b8c446eb8196.png)

**Comment by stephenlb** [comment]
Hi @skylilack it's set incorrectly.

The **"Key"** must be **`Ocp-Apim-Subscription-Key`** and the **"Value"** must be **`4d57d8e3a8c7433590c09fc1a000000`**.

**Comment by skylilack** [comment]
Man, we have progress. But again, fate brings us trials
![Screenshot_15](https://user-images.githubusercontent.com/64641588/81125245-47975380-8f40-11ea-80fe-9d74a5f29307.png)

**Comment by stephenlb** [comment]
Ah okay. So you got the first part of the vault setting correct.

`Your Microsoft key is invalid`.  Double check you are using the right Microsoft Key.

**Comment by skylilack** [comment]
![Screenshot_16](https://user-images.githubusercontent.com/64641588/81126129-0bb1bd80-8f43-11ea-871c-e0e2fd6a4374.png)

**Comment by stephenlb** [comment]
Also make sure to restart once the key is correct.

![image](https://user-images.githubusercontent.com/45214/81126507-53f3c000-8ef0-11ea-935a-b18610353296.png)


Should be working!

**Comment by skylilack** [comment]
I did it.

**Comment by stephenlb** [comment]
In ours, we are using Key 1 from Microsoft website.  It looks like the one you are sharing.  

401 means invalid Key.  Is there some sort of activation that needs to happen on the Microsoft side?

**Comment by skylilack** [comment]
I activated the free version
![Screenshot_18](https://user-images.githubusercontent.com/64641588/81127150-fa1de500-8f45-11ea-81b5-e0b7c6b5da45.png)

**Comment by skylilack** [comment]
b12a49bd45404fc1a0e0eaa8f2df0180    
this is my key please check it. Then I will update it

**Comment by stephenlb** [comment]
Checking

**Comment by stephenlb** [comment]
![image](https://user-images.githubusercontent.com/45214/81128712-c9628f00-8ef6-11ea-9a63-b04093e0e240.png)
invalid API Key ( yup! )

Got the same as you.  For some reason that key isn't working.

**Comment by stephenlb** [comment]
![image](https://user-images.githubusercontent.com/45214/81129072-0418f700-8ef8-11ea-9375-78eddff85aa7.png)
This screenshot, shows what it looks like with an active key.

**Comment by skylilack** [comment]
Thank you, I'll try to fix the key, I'll write it off tomorrow

**Comment by skylilack** [comment]
I am using a key from Azure cognitive servies. Is this the right application? If so, is a free subscription suitable or not?

**Comment by stephenlb** [comment]
Microsoft Translator V3:  https://docs.microsoft.com/en-us/azure/cognitive-services/translator/migrate-to-v3

Microsoft Translator V3 Authentication Key:  https://docs.microsoft.com/en-us/azure/cognitive-services/translator/migrate-to-v3#authentication-key

**Comment by stephenlb** [comment]
We need the `Ocp-Apim-Subscription-Key`: https://docs.microsoft.com/en-us/azure/cognitive-services/translator/reference/v3-0-reference#secret-key

**Comment by skylilack** [comment]
Maybe I'm doing everything right. But Microsoft does not allow me to use the key, because my ip is Russian. or due to the fact that I registered an account with a Polish number. And the pubnub service uses American ip. But these are just guesses

**Comment by skylilack** [comment]
Hallelujah!!! The problem was in the subscription region

**Comment by stephenlb** [comment]
Nice!

**Comment by stephenlb** [comment]
Good find

**Comment by skylilack** [comment]
I replaced pub sub but nothing happens
![Screenshot_21](https://user-images.githubusercontent.com/64641588/81223386-91d70e00-8fee-11ea-8841-7282bad58135.png)
![Screenshot_22](https://user-images.githubusercontent.com/64641588/81223387-93083b00-8fee-11ea-9383-2a5f88181a3b.png)

**Comment by skylilack** [comment]
showing that everything works fine
![Screenshot_23](https://user-images.githubusercontent.com/64641588/81223920-87694400-8fef-11ea-9304-e479ebf21397.png)

**Comment by stephenlb** [comment]
notice the `channel=############` in the URL in OBS.  This needs to match the Channel on the Module.

**Comment by skylilack** [comment]
replaced but nothing happens
![Screenshot_24](https://user-images.githubusercontent.com/64641588/81230422-2135ee80-8ffa-11ea-9414-a88a4ac42112.png)

**Comment by stephenlb** [comment]
Remove `channel-` at the beginning.

**Comment by skylilack** [comment]
Wonderful!
