### ISSUE TITLE
How can I change the language of subtitles?

### ISSUE THREAD

**Issue by kiochan** [stephenlb/twitch-tv-obs-subtitles#3]
My PC has a german Windows 10 installed. I live in Germany too.

But I want to broadcast in English. Should I add some parameters in the query string?

If I want to use some Japanese sentences during speaking, can I set the order of language preferences?

**Comment by stephenlb** [comment]
Hi!  Good question.  This is a common request.  Will find an option for you shortly.

This may do the trick meanwhile: https://www.youtube.com/watch?v=kevhllFZrk4

**Comment by stephenlb** [comment]
The code parameter is as shown in the screenshot.  Will get a URL var setup shortly.

![image](https://user-images.githubusercontent.com/45214/81755478-bd824a00-946d-11ea-9673-beca5e380f43.png)

`spoken.recognition.lang`

`spoken.recognition.lang = "en-US"`

**Comment by stephenlb** [comment]
Okay we have done it.  Will post instructions shortly.

**Comment by stephenlb** [comment]
- Instructions: https://github.com/stephenlb/twitch-tv-obs-subtitles#set-language
 - Example: https://stephenlb.github.io/twitch-tv-obs-subtitles/subtitles.html?language=es-US

**Comment by kiochan** [comment]
Thank you, that's a really quick response. It solves my problem perfectly.

**Comment by stephenlb** [comment]
Excellent, thank you 👍
