### ISSUE TITLE
Subtitles will not clean anymore

### ISSUE THREAD

**Issue by kiochan** [stephenlb/twitch-tv-obs-subtitles#4]
![image](https://user-images.githubusercontent.com/12151173/81820747-4910df00-9531-11ea-8f3f-a4222b83808c.png)

Subtitles will not clean after any pause of speck.

**Comment by stephenlb** [comment]
You can set `maxwords=10` parameter like this: 

> https://stephenlb.github.io/twitch-tv-obs-subtitles/subtitles.html?maxwords=10

Documentation here: https://github.com/stephenlb/twitch-tv-obs-subtitles#set-max-words

Also you can Crop the output in OBS.

There's also a way to crop using CSS like this `bottom:92vh`

> https://stephenlb.github.io/twitch-tv-obs-subtitles/subtitles.html?style=background%3A%23000%3Bfont-weight%3A600%3Btext-transform%3Auppercase%3Btext-shadow%3Anone%3Bpadding%3A10px;bottom:92vh

Change the CSS to match your desired display.

**Comment by stephenlb** [comment]
Creating more examples today:

![closed-caption](https://user-images.githubusercontent.com/45214/81862643-d7c83080-951e-11ea-8f81-fb77bc945c69.gif)

**Comment by stephenlb** [comment]
Also adding Nyan Cat subtitles just in case 😉 

![nyan-preview](https://user-images.githubusercontent.com/45214/81875360-f76a5380-9534-11ea-9600-3eb4eec0a8f6.gif)

https://stephenlb.github.io/twitch-tv-obs-subtitles/subtitles-nyan.html?channel=MYCHANNEL

Since this is an open source and free tool, it's open to fully customize the display any way you like.

**Comment by kiochan** [comment]
First of all, I apologize for my English ability.

What I want to express is that usually I finish a sentence and begin to speak the next sentence. The last sentence will disappear when I begin to speak the next sentence. But now it will continue to be added after the previous sentence.

Is this a new feature?

PS. Nyancat is awesome

**Comment by stephenlb** [comment]
Yes.  You are correct.

Prior to this feature the voice detection algorithm stopped for 0.2 - 1.5 seconds while a new voice recognition session initialized.  The affect was a delay in recognizing your voice, also it would cause the text on the screen to clear.  

The new upgrade is a continuous voice session, without any pauses or delays.  So overall it's an improved voice capture voice-to-text upgrade.  However it's easy to see some may have relied on this.

Shortly will add the option to restore the old recognition algorithm.  Will post an update shortly.

**Comment by stephenlb** [comment]
This is done.

To downgrade the algorithm, use the `continuous=off` parameter.

> https://stephenlb.github.io/twitch-tv-obs-subtitles/subtitles.html?continuous=off

The above link will downgrade your voice-to-text to the old algorithm.

Documentation added https://github.com/stephenlb/twitch-tv-obs-subtitles#original-voice-setting



If you also want to set the language to English, add the `language=en-US` parameter like this:

> https://stephenlb.github.io/twitch-tv-obs-subtitles/subtitles.html?language=en-US&continuous=off

The above link will restore original voice detector and set the language to English.

**Comment by kiochan** [comment]
wow, amazing! thank you very much, that solve my problem perfectly
